#!/usr/bin/env python3

"""DMSpider.

Usage:
    crawl comic [ -p <path> -z ] <url>
    crawl comic [ -p <path> -z ] -f <file>
    crawl chapter [ -p <path> -z ] <url>
    crawl chapter [ -p <path> -z ] -f <file>
    crawl ( -h | --help )
    crawl --version

Options:
    -h --help         Show this screen.
    --version         Show version.
    -f <file>         Input file which have some urls.
    -p <path>         Saved directory.
    -z                Compress folder.
"""


from docopt import docopt

from spider import download


def main(arguments):
    is_comic = arguments["comic"]
    saved_path = arguments["-p"] if arguments["-p"] else None
    if arguments["-f"]:
        with open(arguments["-f"], "r") as f:
            urls = f.readlines()
    else:
        urls = [arguments["<url>"]]
    download(urls, is_comic, path=saved_path, zip=arguments["-z"])


if __name__ == "__main__":
    arguments = docopt(__doc__, version="DMSpider 1.1")
    main(arguments)
